### PR TITLE
added welcome page

### PR DESCRIPTION
**Pull request by Pratik521992**
Added welcome page.
for now i have kept the old components.

FYI there is a video background
please do run and check once

### CODE REVIEW

**Comment by arnabchat90** [comment]
please remove package-lock, also give a screen shot of the ui

**Review by arnabchat90 — CHANGES_REQUESTED** [review]
Please remove conflict.
Also please add screenshots and more details about the welcome page

**Comment by Pratik521992** [comment]
welcome-page

**Comment by Pratik521992** [comment]
@arnabchat90  @SahilRS200  i have attached the screenshot.

The background is a small video which plays on a continuous loop.

Let me know your views and further changes/enhancements if required...

**Review by SahilRS200 — APPROVED** [review]
Looks good

**Comment by Pratik521992** [comment]
@arnabchat90 

I have removed package-lock.json file and attached screenshot of welcome page above.
Let me know if anything else is req...

**Pull request merged**
